spring:
  application:
    name: app

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
output:
  ansi:
  enabled: always    # цветной вывод логотипа
logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"  # кастомный формат даты в логах
app:
  welcome-message: "Welcome to Spring blog!"  # наше кастомное сообщение
  default-user-password: "qwerty"
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs
sentry:
  dsn: ${SENTRY_DSN:}
  enabled: ${SENTRY_ENABLED:true}
  traces-sample-rate: 1.0
  send-default-pii: true
  exception-resolver-order: -2147483647
