name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build + Test + Coverage + Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew clean test jacocoTestReport sonar \
            -Dsonar.projectKey=alexeymelekhov-dev_spring-boot-project-99 \
            -Dsonar.organization=alexeymelekhov-dev \
            -Dsonar.host.url=https://sonarcloud.io